server:
  port: 8999


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      
      #Policy-Service     
        - id: policy-service
          uri: lb://policy-service
          predicates:
            - Path=/policy/**
            
      #Member-Services
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member/**
            
      #Cliam Services
        - id: claim-service
          uri: lb://claim-service
          predicates:
            - Path=/claim/**
          
     #Cliam Services
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/authorization/** 
      
      
      
      
      #Eureka-Server  
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
     
     #Eureka-Server static resource Rotue
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
  
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka          
            